# This is basically a set of instructions for building a docker image.
# The instructions are based on the instructions for building a docker image
# from the official documentation.

# here firstly we are using node version 17-alpine as the base image.

FROM node:17-alpine